categories:
  - title: 'Features'
    label: 'kind/feature'
  - title: 'Bug Fixes'
    label: 'kind/bug'
  - title: 'Maintenance'
    label: 'kind/chore'
  - title: 'Performance Improvements'
    label: 'kind/performance'
exclude-labels:
  - 'kind/test'
  - 'kind/ci'
  - 'kind/build'
  - 'kind/refactor'
  - 'kind/style'
replacers:
  - search: '/\w+ ?[\(\w\)]*: (.*)/g'
    replace: '$1'
change-template: '- $TITLE (#$NUMBER)...'
template: |
  ## What's Changed since $PREVIOUS_TAG

  $CHANGES
