 on:
   push:
     branches:
       - master
 name: release-please
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
        - uses: GoogleCloudPlatform/release-please-action@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release-type: simple
            package-name: repobot
        - uses: actions/checkout@v2
          if: ${{ steps.release.outputs.release_created }}
        - name: Set up Go 1.x
          uses: actions/setup-go@v2
          with:
            go-version: ^1.15
          id: go
          if: ${{ steps.release.outputs.release_created }}

        - name: echo output
          run: echo "${{ steps.release.outputs }}"
        - name: Get dependencies
          run: |
            go get -v -t -d ./...
            if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
            fi
          if: ${{ steps.release.outputs.release_created }}

        - name: Build
          run: go build -v ./...
          if: ${{ steps.release.outputs.release_created }}
