on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-backend:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
          extra-files: |
            deploy/docker-compose.prod.yml
          package-name: testrepo
      - name: Show output
        run: echo ${{ steps.release.outputs.release_created }}

  build-deploy: 
    runs-on: ubuntu-latest
    needs: release-backend
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Determine version
        run: |
          VERSION=`cat version.txt`
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi

      - name: Build
        run: go build -ldflags '-X main.version='$VERSION -v -o screenshot  ./...

      #- name: Deploy with Ansible
      #  uses: arillso/action.playbook@master
      #  with:
      #    playbook: .ansible/deploy.yml
      #    inventory: .ansible/inventory/hosts
      #    ssh_common_args: "-o StrictHostKeyChecking=no"
      #    user: root
      #    private_key: "${{ secrets.SSH_KEY }}"
